name: counter-build-test
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Download Dependancies 
        run: |
           sudo apt install lintian
           pip3 install pytest
      - name: Build Project
        run: |
          make build
      - name: Test Project
        run: |
          make test
      - name: Build Debian File
        run: |
          make build-deb
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb artifact
          path: counter-v2.0.0.deb
      - name: Run lint deb
        run: |
          make lint-deb
      - run: echo "ğŸ This job's status is ${{ job.status }}."
