name: test
run-name: ${{ github.actor }} is running the test github action ğŸš€
on: [push]
jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Download Dependancies 
        run: |
           sudo apt install lintian
           pip3 install pytest

      - name: Test Project
        run: |
          make test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      
